services:
  - type: web
    name: oosm-api
    runtime: docker
    repo: https://github.com/x-dev-grp/oosm
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: frankfurt
    plan: free
    autoDeployTrigger: off
    healthCheckPath: /actuator/health/liveness

  - type: web
    name: oosm-web
    runtime: docker
    repo: https://github.com/x-dev-grp/osm-ms-fe
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: frankfurt
    plan: free
    autoDeployTrigger: off
    healthCheckPath: /
    envVars:
      - key: BACKEND_HOSTPORT
        fromService:
          name: oosm-api
          type: web
          property: hostport
