# Add missing explicit imports after wildcard removal
$ErrorActionPreference = "Stop"
. "$PSScriptRoot\Write-Utf8NoBom.ps1"
$base = "C:\OSM 2.0\oosm\modules\production\src\main\java"

$typeImports = @{
    "BaseTypeDto" = "com.xdev.ooms.production.basetype.dto.BaseTypeDto"
    "BaseType" = "com.xdev.ooms.production.basetype.entity.BaseType"
    "GenericRepository" = "com.xdev.ooms.production.basetype.repository.GenericRepository"
    "GenericTypeService" = "com.xdev.ooms.production.basetype.service.GenericTypeService"
    "OilTransactionDTO" = "com.xdev.ooms.production.oiltransaction.dto.OilTransactionDTO"
    "OilTransaction" = "com.xdev.ooms.production.oiltransaction.entity.OilTransaction"
    "OilTransactionRepository" = "com.xdev.ooms.production.oiltransaction.repository.OilTransactionRepository"
    "OilTransactionService" = "com.xdev.ooms.production.oiltransaction.service.OilTransactionService"
    "UnifiedDeliveryDTO" = "com.xdev.ooms.production.unifieddelivery.dto.UnifiedDeliveryDTO"
    "UnifiedDelivery" = "com.xdev.ooms.production.unifieddelivery.entity.UnifiedDelivery"
    "DeliveryRepository" = "com.xdev.ooms.production.unifieddelivery.repository.DeliveryRepository"
    "DeliveryWithNextIdDto" = "com.xdev.ooms.production.unifieddelivery.dto.DeliveryWithNextIdDto"
    "ExchangePricingDto" = "com.xdev.ooms.production.unifieddelivery.dto.ExchangePricingDto"
    "PaymentDTO" = "com.xdev.ooms.production.unifieddelivery.dto.PaymentDTO"
    "UnifiedDeliveryService" = "com.xdev.ooms.production.unifieddelivery.service.UnifiedDeliveryService"
    "StorageUnitDto" = "com.xdev.ooms.production.storageunit.dto.StorageUnitDto"
    "StorageUnit" = "com.xdev.ooms.production.storageunit.entity.StorageUnit"
    "StorageUnitRepo" = "com.xdev.ooms.production.storageunit.repository.StorageUnitRepo"
    "StorageUnitService" = "com.xdev.ooms.production.storageunit.service.StorageUnitService"
    "SupplierDto" = "com.xdev.ooms.production.supplier.dto.SupplierDto"
    "Supplier" = "com.xdev.ooms.production.supplier.entity.Supplier"
    "SupplierRepository" = "com.xdev.ooms.production.supplier.repository.SupplierRepository"
    "SupplierTypeService" = "com.xdev.ooms.production.supplier.service.SupplierTypeService"
    "WasteDTO" = "com.xdev.ooms.production.waste.dto.WasteDTO"
    "Waste" = "com.xdev.ooms.production.waste.entity.Waste"
    "WasteRepository" = "com.xdev.ooms.production.waste.repository.WasteRepository"
    "WasteService" = "com.xdev.ooms.production.waste.service.WasteService"
    "OilSaleDTO" = "com.xdev.ooms.production.oilsale.dto.OilSaleDTO"
    "OilSaleCreateRequest" = "com.xdev.ooms.production.oilsale.dto.OilSaleCreateRequest"
    "OilSale" = "com.xdev.ooms.production.oilsale.entity.OilSale"
    "OilSaleRepository" = "com.xdev.ooms.production.oilsale.repository.OilSaleRepository"
    "OilSaleService" = "com.xdev.ooms.production.oilsale.service.OilSaleService"
    "OilContainerDTO" = "com.xdev.ooms.production.oilcontainer.dto.OilContainerDTO"
    "OilContainer" = "com.xdev.ooms.production.oilcontainer.entity.OilContainer"
    "OilContainerRepository" = "com.xdev.ooms.production.oilcontainer.repository.OilContainerRepository"
    "OilContainerService" = "com.xdev.ooms.production.oilcontainer.service.OilContainerService"
    "OilContainerSaleDto" = "com.xdev.ooms.production.oilcontainersale.dto.OilContainerSaleDto"
    "OilContainerSale" = "com.xdev.ooms.production.oilcontainersale.entity.OilContainerSale"
    "OilContainerSaleRepo" = "com.xdev.ooms.production.oilcontainersale.repository.OilContainerSaleRepo"
    "OilContainerSalesService" = "com.xdev.ooms.production.oilcontainersale.service.OilContainerSalesService"
    "MillMachineDto" = "com.xdev.ooms.production.millmachine.dto.MillMachineDto"
    "MillMachine" = "com.xdev.ooms.production.millmachine.entity.MillMachine"
    "MillMachineRepository" = "com.xdev.ooms.production.millmachine.repository.MillMachineRepository"
    "MillMachineService" = "com.xdev.ooms.production.millmachine.service.MillMachineService"
    "MachinePlanDto" = "com.xdev.ooms.production.machineplan.dto.MachinePlanDto"
    "MachinePlan" = "com.xdev.ooms.production.machineplan.entity.MachinePlan"
    "MachinePlanRepository" = "com.xdev.ooms.production.machineplan.repository.MachinePlanRepository"
    "MachinePlanService" = "com.xdev.ooms.production.machineplan.service.MachinePlanService"
    "MillPlanDTO" = "com.xdev.ooms.production.planning.dto.MillPlanDTO"
    "PlanItemDTO" = "com.xdev.ooms.production.planning.dto.PlanItemDTO"
    "PlanItemType" = "com.xdev.ooms.production.planning.dto.PlanItemType"
    "PlanningSaveRequest" = "com.xdev.ooms.production.planning.dto.PlanningSaveRequest"
    "PlanningService" = "com.xdev.ooms.production.planning.service.PlanningService"
    "TransporterDTO" = "com.xdev.ooms.production.transporter.dto.TransporterDTO"
    "Transporter" = "com.xdev.ooms.production.transporter.entity.Transporter"
    "TransporterRepository" = "com.xdev.ooms.production.transporter.repository.TransporterRepository"
    "TransporterService" = "com.xdev.ooms.production.transporter.service.TransporterService"
    "ParameterDto" = "com.xdev.ooms.production.parameter.dto.ParameterDto"
    "Parameter" = "com.xdev.ooms.production.parameter.entity.Parameter"
    "ParameterRepo" = "com.xdev.ooms.production.parameter.repository.ParameterRepo"
    "ParameterService" = "com.xdev.ooms.production.parameter.service.ParameterService"
    "QualityControlResultDto" = "com.xdev.ooms.production.qualitycontrol.dto.QualityControlResultDto"
    "QualityControlRuleDto" = "com.xdev.ooms.production.qualitycontrol.dto.QualityControlRuleDto"
    "QualityControlResult" = "com.xdev.ooms.production.qualitycontrol.entity.QualityControlResult"
    "QualityControlRule" = "com.xdev.ooms.production.qualitycontrol.entity.QualityControlRule"
    "QualityControlResultRepository" = "com.xdev.ooms.production.qualitycontrol.repository.QualityControlResultRepository"
    "QualityControlRuleRepository" = "com.xdev.ooms.production.qualitycontrol.repository.QualityControlRuleRepository"
    "QualityControlResultService" = "com.xdev.ooms.production.qualitycontrol.service.QualityControlResultService"
    "QualityControlRuleService" = "com.xdev.ooms.production.qualitycontrol.service.QualityControlRuleService"
    "FiltrationOperation" = "com.xdev.ooms.production.filtration.entity.FiltrationOperation"
    "FiltrationOperationDto" = "com.xdev.ooms.production.filtration.dto.FiltrationOperationDto"
    "FiltrationRequestDto" = "com.xdev.ooms.production.filtration.dto.FiltrationRequestDto"
    "FiltrationResultDto" = "com.xdev.ooms.production.filtration.dto.FiltrationResultDto"
    "FiltrationStatus" = "com.xdev.ooms.production.filtration.dto.FiltrationStatus"
    "FiltrationStepDto" = "com.xdev.ooms.production.filtration.dto.FiltrationStepDto"
    "FiltrationAnalyticsDto" = "com.xdev.ooms.production.filtration.dto.FiltrationAnalyticsDto"
    "FiltrationCompletionDto" = "com.xdev.ooms.production.filtration.dto.FiltrationCompletionDto"
    "UpdateFiltrationStatusDto" = "com.xdev.ooms.production.filtration.dto.UpdateFiltrationStatusDto"
    "FiltrationOperationRepo" = "com.xdev.ooms.production.filtration.repository.FiltrationOperationRepo"
    "FiltrationService" = "com.xdev.ooms.production.filtration.service.FiltrationService"
    "TraceabilityLot" = "com.xdev.ooms.production.genealogy.entity.TraceabilityLot"
    "TraceabilitySourceType" = "com.xdev.ooms.production.genealogy.enums.TraceabilitySourceType"
    "GenealogyDto" = "com.xdev.ooms.production.genealogy.dto.GenealogyDto"
    "RootSourceDto" = "com.xdev.ooms.production.genealogy.dto.RootSourceDto"
    "GlobalLotDto" = "com.xdev.ooms.production.genealogy.dto.GlobalLotDto"
    "IntakeStepDto" = "com.xdev.ooms.production.genealogy.dto.IntakeStepDto"
    "SyncRequestDTO" = "com.xdev.ooms.production.genealogy.dto.SyncRequestDTO"
    "SyncStatisticsDTO" = "com.xdev.ooms.production.genealogy.dto.SyncStatisticsDTO"
    "TraceabilityLotRepository" = "com.xdev.ooms.production.genealogy.repository.TraceabilityLotRepository"
    "GenealogyService" = "com.xdev.ooms.production.genealogy.service.GenealogyService"
    "TraceabilityLotService" = "com.xdev.ooms.production.genealogy.service.TraceabilityLotService"
    "ProdAnalyticsService" = "com.xdev.ooms.production.analytics.service.ProdAnalyticsService"
    "ApiResponse" = "com.xdev.ooms.production.dto.ApiResponse"
}

$javaFiles = Get-ChildItem -Path $base -Recurse -Filter "*.java"

foreach ($file in $javaFiles) {
    $content = Get-Content $file.FullName -Raw -Encoding UTF8
    $needed = @()
    foreach ($entry in $typeImports.GetEnumerator()) {
        $simple = $entry.Key
        $fqcn = $entry.Value
        if ($content -match "\b$simple\b" -and $content -notmatch "import $([regex]::Escape($fqcn));") {
            $needed += "import $fqcn;"
        }
    }
    if ($needed.Count -eq 0) { continue }

    if ($content -match '(?s)(package [^;]+;\r?\n\r?\n)') {
        $importsBlock = ($needed | Sort-Object -Unique) -join "`n"
        $newContent = $content -replace '(?s)(package [^;]+;\r?\n\r?\n)', "`$1$importsBlock`n`n"
        Write-Utf8NoBomFile -Path $file.FullName -Content $newContent
        Write-Host "Added $($needed.Count) imports to $($file.Name)"
    }
}

Write-Host "Missing import injection complete."
