# Update imports across oosm after production DTO co-location
$ErrorActionPreference = "Stop"
. "$PSScriptRoot\Write-Utf8NoBom.ps1"
$root = "C:\OSM 2.0\oosm"

# old import suffix -> new full import path (sorted longest-first when applied)
$replacements = [ordered]@{
    "com.xdev.ooms.production.dto.OilContainerSaleDto" = "com.xdev.ooms.production.oilcontainersale.dto.OilContainerSaleDto"
    "com.xdev.ooms.production.dto.QualityControlResultDto" = "com.xdev.ooms.production.qualitycontrol.dto.QualityControlResultDto"
    "com.xdev.ooms.production.dto.QualityControlRuleDto" = "com.xdev.ooms.production.qualitycontrol.dto.QualityControlRuleDto"
    "com.xdev.ooms.production.dto.UpdateFiltrationStatusDto" = "com.xdev.ooms.production.filtration.dto.UpdateFiltrationStatusDto"
    "com.xdev.ooms.production.dto.FiltrationCompletionDto" = "com.xdev.ooms.production.filtration.dto.FiltrationCompletionDto"
    "com.xdev.ooms.production.dto.FiltrationAnalyticsDto" = "com.xdev.ooms.production.filtration.dto.FiltrationAnalyticsDto"
    "com.xdev.ooms.production.dto.FiltrationOperationDto" = "com.xdev.ooms.production.filtration.dto.FiltrationOperationDto"
    "com.xdev.ooms.production.dto.FiltrationRequestDto" = "com.xdev.ooms.production.filtration.dto.FiltrationRequestDto"
    "com.xdev.ooms.production.dto.FiltrationResultDto" = "com.xdev.ooms.production.filtration.dto.FiltrationResultDto"
    "com.xdev.ooms.production.dto.FiltrationStepDto" = "com.xdev.ooms.production.filtration.dto.FiltrationStepDto"
    "com.xdev.ooms.production.dto.DeliveryWithNextIdDto" = "com.xdev.ooms.production.unifieddelivery.dto.DeliveryWithNextIdDto"
    "com.xdev.ooms.production.dto.UnifiedDeliveryDTO" = "com.xdev.ooms.production.unifieddelivery.dto.UnifiedDeliveryDTO"
    "com.xdev.ooms.production.dto.ExchangePricingDto" = "com.xdev.ooms.production.unifieddelivery.dto.ExchangePricingDto"
    "com.xdev.ooms.production.dto.OilSaleCreateRequest" = "com.xdev.ooms.production.oilsale.dto.OilSaleCreateRequest"
    "com.xdev.ooms.production.dto.PlanningSaveRequest" = "com.xdev.ooms.production.planning.dto.PlanningSaveRequest"
    "com.xdev.ooms.production.dto.OilTransactionDTO" = "com.xdev.ooms.production.oiltransaction.dto.OilTransactionDTO"
    "com.xdev.ooms.production.dto.SyncStatisticsDTO" = "com.xdev.ooms.production.genealogy.dto.SyncStatisticsDTO"
    "com.xdev.ooms.production.dto.OilContainerDTO" = "com.xdev.ooms.production.oilcontainer.dto.OilContainerDTO"
    "com.xdev.ooms.production.dto.FiltrationStatus" = "com.xdev.ooms.production.filtration.dto.FiltrationStatus"
    "com.xdev.ooms.production.dto.StorageUnitDto" = "com.xdev.ooms.production.storageunit.dto.StorageUnitDto"
    "com.xdev.ooms.production.dto.TransporterDTO" = "com.xdev.ooms.production.transporter.dto.TransporterDTO"
    "com.xdev.ooms.production.dto.MachinePlanDto" = "com.xdev.ooms.production.machineplan.dto.MachinePlanDto"
    "com.xdev.ooms.production.dto.MillMachineDto" = "com.xdev.ooms.production.millmachine.dto.MillMachineDto"
    "com.xdev.ooms.production.dto.ParameterDto" = "com.xdev.ooms.production.parameter.dto.ParameterDto"
    "com.xdev.ooms.production.dto.SyncRequestDTO" = "com.xdev.ooms.production.genealogy.dto.SyncRequestDTO"
    "com.xdev.ooms.production.dto.RootSourceDto" = "com.xdev.ooms.production.genealogy.dto.RootSourceDto"
    "com.xdev.ooms.production.dto.GlobalLotDto" = "com.xdev.ooms.production.genealogy.dto.GlobalLotDto"
    "com.xdev.ooms.production.dto.IntakeStepDto" = "com.xdev.ooms.production.genealogy.dto.IntakeStepDto"
    "com.xdev.ooms.production.dto.GenealogyDto" = "com.xdev.ooms.production.genealogy.dto.GenealogyDto"
    "com.xdev.ooms.production.dto.PlanItemType" = "com.xdev.ooms.production.planning.dto.PlanItemType"
    "com.xdev.ooms.production.dto.PlanItemDTO" = "com.xdev.ooms.production.planning.dto.PlanItemDTO"
    "com.xdev.ooms.production.dto.MillPlanDTO" = "com.xdev.ooms.production.planning.dto.MillPlanDTO"
    "com.xdev.ooms.production.dto.BaseTypeDto" = "com.xdev.ooms.production.basetype.dto.BaseTypeDto"
    "com.xdev.ooms.production.dto.SupplierDto" = "com.xdev.ooms.production.supplier.dto.SupplierDto"
    "com.xdev.ooms.production.dto.OilSaleDTO" = "com.xdev.ooms.production.oilsale.dto.OilSaleDTO"
    "com.xdev.ooms.production.dto.PaymentDTO" = "com.xdev.ooms.production.unifieddelivery.dto.PaymentDTO"
    "com.xdev.ooms.production.dto.WasteDTO" = "com.xdev.ooms.production.waste.dto.WasteDTO"

    "com.xdev.ooms.production.model.QualityControlResult" = "com.xdev.ooms.production.qualitycontrol.entity.QualityControlResult"
    "com.xdev.ooms.production.model.QualityControlRule" = "com.xdev.ooms.production.qualitycontrol.entity.QualityControlRule"
    "com.xdev.ooms.production.model.TraceabilitySourceType" = "com.xdev.ooms.production.genealogy.enums.TraceabilitySourceType"
    "com.xdev.ooms.production.model.OilContainerSale" = "com.xdev.ooms.production.oilcontainersale.entity.OilContainerSale"
    "com.xdev.ooms.production.model.FiltrationOperation" = "com.xdev.ooms.production.filtration.entity.FiltrationOperation"
    "com.xdev.ooms.production.model.UnifiedDelivery" = "com.xdev.ooms.production.unifieddelivery.entity.UnifiedDelivery"
    "com.xdev.ooms.production.model.OilTransaction" = "com.xdev.ooms.production.oiltransaction.entity.OilTransaction"
    "com.xdev.ooms.production.model.TraceabilityLot" = "com.xdev.ooms.production.genealogy.entity.TraceabilityLot"
    "com.xdev.ooms.production.model.OilContainer" = "com.xdev.ooms.production.oilcontainer.entity.OilContainer"
    "com.xdev.ooms.production.model.MachinePlan" = "com.xdev.ooms.production.machineplan.entity.MachinePlan"
    "com.xdev.ooms.production.model.MillMachine" = "com.xdev.ooms.production.millmachine.entity.MillMachine"
    "com.xdev.ooms.production.model.StorageUnit" = "com.xdev.ooms.production.storageunit.entity.StorageUnit"
    "com.xdev.ooms.production.model.Transporter" = "com.xdev.ooms.production.transporter.entity.Transporter"
    "com.xdev.ooms.production.model.OilSale" = "com.xdev.ooms.production.oilsale.entity.OilSale"
    "com.xdev.ooms.production.model.Parameter" = "com.xdev.ooms.production.parameter.entity.Parameter"
    "com.xdev.ooms.production.model.BaseType" = "com.xdev.ooms.production.basetype.entity.BaseType"
    "com.xdev.ooms.production.model.Supplier" = "com.xdev.ooms.production.supplier.entity.Supplier"
    "com.xdev.ooms.production.model.Waste" = "com.xdev.ooms.production.waste.entity.Waste"

    "com.xdev.ooms.production.repository.QualityControlResultRepository" = "com.xdev.ooms.production.qualitycontrol.repository.QualityControlResultRepository"
    "com.xdev.ooms.production.repository.QualityControlRuleRepository" = "com.xdev.ooms.production.qualitycontrol.repository.QualityControlRuleRepository"
    "com.xdev.ooms.production.repository.FiltrationOperationRepo" = "com.xdev.ooms.production.filtration.repository.FiltrationOperationRepo"
    "com.xdev.ooms.production.repository.OilContainerSaleRepo" = "com.xdev.ooms.production.oilcontainersale.repository.OilContainerSaleRepo"
    "com.xdev.ooms.production.repository.OilTransactionRepository" = "com.xdev.ooms.production.oiltransaction.repository.OilTransactionRepository"
    "com.xdev.ooms.production.repository.TraceabilityLotRepository" = "com.xdev.ooms.production.genealogy.repository.TraceabilityLotRepository"
    "com.xdev.ooms.production.repository.OilContainerRepository" = "com.xdev.ooms.production.oilcontainer.repository.OilContainerRepository"
    "com.xdev.ooms.production.repository.MachinePlanRepository" = "com.xdev.ooms.production.machineplan.repository.MachinePlanRepository"
    "com.xdev.ooms.production.repository.MillMachineRepository" = "com.xdev.ooms.production.millmachine.repository.MillMachineRepository"
    "com.xdev.ooms.production.repository.TransporterRepository" = "com.xdev.ooms.production.transporter.repository.TransporterRepository"
    "com.xdev.ooms.production.repository.OilSaleRepository" = "com.xdev.ooms.production.oilsale.repository.OilSaleRepository"
    "com.xdev.ooms.production.repository.StorageUnitRepo" = "com.xdev.ooms.production.storageunit.repository.StorageUnitRepo"
    "com.xdev.ooms.production.repository.SupplierRepository" = "com.xdev.ooms.production.supplier.repository.SupplierRepository"
    "com.xdev.ooms.production.repository.DeliveryRepository" = "com.xdev.ooms.production.unifieddelivery.repository.DeliveryRepository"
    "com.xdev.ooms.production.repository.GenericRepository" = "com.xdev.ooms.production.basetype.repository.GenericRepository"
    "com.xdev.ooms.production.repository.WasteRepository" = "com.xdev.ooms.production.waste.repository.WasteRepository"
    "com.xdev.ooms.production.repository.ParameterRepo" = "com.xdev.ooms.production.parameter.repository.ParameterRepo"

    "com.xdev.ooms.production.service.QualityControlResultService" = "com.xdev.ooms.production.qualitycontrol.service.QualityControlResultService"
    "com.xdev.ooms.production.service.QualityControlRuleService" = "com.xdev.ooms.production.qualitycontrol.service.QualityControlRuleService"
    "com.xdev.ooms.production.service.OilContainerSalesService" = "com.xdev.ooms.production.oilcontainersale.service.OilContainerSalesService"
    "com.xdev.ooms.production.service.UnifiedDeliveryService" = "com.xdev.ooms.production.unifieddelivery.service.UnifiedDeliveryService"
    "com.xdev.ooms.production.service.TraceabilityLotService" = "com.xdev.ooms.production.genealogy.service.TraceabilityLotService"
    "com.xdev.ooms.production.service.OilTransactionService" = "com.xdev.ooms.production.oiltransaction.service.OilTransactionService"
    "com.xdev.ooms.production.service.OilContainerService" = "com.xdev.ooms.production.oilcontainer.service.OilContainerService"
    "com.xdev.ooms.production.service.MachinePlanService" = "com.xdev.ooms.production.machineplan.service.MachinePlanService"
    "com.xdev.ooms.production.service.MillMachineService" = "com.xdev.ooms.production.millmachine.service.MillMachineService"
    "com.xdev.ooms.production.service.StorageUnitService" = "com.xdev.ooms.production.storageunit.service.StorageUnitService"
    "com.xdev.ooms.production.service.SupplierTypeService" = "com.xdev.ooms.production.supplier.service.SupplierTypeService"
    "com.xdev.ooms.production.service.TransporterService" = "com.xdev.ooms.production.transporter.service.TransporterService"
    "com.xdev.ooms.production.service.ProdAnalyticsService" = "com.xdev.ooms.production.analytics.service.ProdAnalyticsService"
    "com.xdev.ooms.production.service.GenericTypeService" = "com.xdev.ooms.production.basetype.service.GenericTypeService"
    "com.xdev.ooms.production.service.FiltrationService" = "com.xdev.ooms.production.filtration.service.FiltrationService"
    "com.xdev.ooms.production.service.ParameterService" = "com.xdev.ooms.production.parameter.service.ParameterService"
    "com.xdev.ooms.production.service.PlanningService" = "com.xdev.ooms.production.planning.service.PlanningService"
    "com.xdev.ooms.production.service.GenealogyService" = "com.xdev.ooms.production.genealogy.service.GenealogyService"
    "com.xdev.ooms.production.service.OilSaleService" = "com.xdev.ooms.production.oilsale.service.OilSaleService"
    "com.xdev.ooms.production.service.WasteService" = "com.xdev.ooms.production.waste.service.WasteService"

    "com.xdev.ooms.production.controller.QualityControlResultController" = "com.xdev.ooms.production.qualitycontrol.controller.QualityControlResultController"
    "com.xdev.ooms.production.controller.QualityControlRuleController" = "com.xdev.ooms.production.qualitycontrol.controller.QualityControlRuleController"
    "com.xdev.ooms.production.controller.OilContainerSalesController" = "com.xdev.ooms.production.oilcontainersale.controller.OilContainerSalesController"
    "com.xdev.ooms.production.controller.UnifiedDeliveryController" = "com.xdev.ooms.production.unifieddelivery.controller.UnifiedDeliveryController"
    "com.xdev.ooms.production.controller.OilTransactionController" = "com.xdev.ooms.production.oiltransaction.controller.OilTransactionController"
    "com.xdev.ooms.production.controller.OilContainerController" = "com.xdev.ooms.production.oilcontainer.controller.OilContainerController"
    "com.xdev.ooms.production.controller.StorageUnitController" = "com.xdev.ooms.production.storageunit.controller.StorageUnitController"
    "com.xdev.ooms.production.controller.SupplierTypeController" = "com.xdev.ooms.production.supplier.controller.SupplierTypeController"
    "com.xdev.ooms.production.controller.TransporterController" = "com.xdev.ooms.production.transporter.controller.TransporterController"
    "com.xdev.ooms.production.controller.MillMachineController" = "com.xdev.ooms.production.millmachine.controller.MillMachineController"
    "com.xdev.ooms.production.controller.GenericTypeController" = "com.xdev.ooms.production.basetype.controller.GenericTypeController"
    "com.xdev.ooms.production.controller.FiltrationController" = "com.xdev.ooms.production.filtration.controller.FiltrationController"
    "com.xdev.ooms.production.controller.ParameterController" = "com.xdev.ooms.production.parameter.controller.ParameterController"
    "com.xdev.ooms.production.controller.PlanningController" = "com.xdev.ooms.production.planning.controller.PlanningController"
    "com.xdev.ooms.production.controller.GenealogyController" = "com.xdev.ooms.production.genealogy.controller.GenealogyController"
    "com.xdev.ooms.production.controller.AnalyticsController" = "com.xdev.ooms.production.analytics.controller.AnalyticsController"
    "com.xdev.ooms.production.controller.OilSaleController" = "com.xdev.ooms.production.oilsale.controller.OilSaleController"
    "com.xdev.ooms.production.controller.WasteController" = "com.xdev.ooms.production.waste.controller.WasteController"
}

$javaFiles = Get-ChildItem -Path $root -Recurse -Filter "*.java" | Where-Object { $_.FullName -notmatch '\\legacy\\' }

foreach ($file in $javaFiles) {
    $content = Get-Content $file.FullName -Raw -Encoding UTF8
    $original = $content
    foreach ($entry in $replacements.GetEnumerator()) {
        $content = $content.Replace($entry.Key, $entry.Value)
    }
    if ($content -ne $original) {
        Write-Utf8NoBomFile -Path $file.FullName -Content $content
        Write-Host "Updated: $($file.FullName)"
    }
}

Write-Host "Import replacement complete."
